index.js
It was bothering me that we were calling different versions of `assign` and doing it twice [my fault]. This is more consistent and less redundant [but no actual change to logic].
=> Remove duplication in updating options and binding the run function

.editorconfig, README.md, index.js, test/index.js
- consistent tense in test suite
- corrected editorconfig for markdown files
- use `.have.length` assertion
=> More minor code tweaks

test/index.js
Resolves #12 
EDIT: having read through https://github.com/webpack/docs/wiki/list-of-plugins#noerrorsplugin
unless I'm missing something, it seems like the plugin is working correctly because it will prevent the `emit` phase by throwing an error when it is asked to.
cc @vieron @erikahlswede @msaforrian
=> tests: interop with NoErrorsPlugin

README.md
See https://github.com/vieron/stylelint-webpack-plugin/issues/7#issuecomment-247270888
Resolves #7.
=> Remove "inherits from webpack" from example

index.js, lib/run-compilation.js, test/index.js
I've added this plugin to `create-react-app` in facebookincubator/create-react-app#1216. This pull request improves the display of the warnings / errors and makes them appear in watch mode too.
=> Fixes for watch mode of create-react-app

README.md, index.js, package.json, yarn.lock
Changed in stylelint/stylelint#2134
=> Fix stylelint formatter path

package.json, test/helpers/pack.js, test/helpers/setup.js, test/helpers/webpack.js, test/index.js, yarn.lock
Using this plugin with webpack 2 currently installs 2 versions of webpack.
Resolves #38.
=> fix: move webpack to a peer dependency and allow webpack 2

README.md, lib/run-compilation.js, package.json, test/index.test.js, test/lib/lint-dirty-modules-plugin.test.js
This option allows you to log errors as warnings, preventing
Webpack dev server from aborting compilation.
=> Fixes #65: Add `emitErrors` option

lib/run-compilation.js, package.json, test/index.test.js
Hi!
This is an attempt to fix https://github.com/JaKXz/stylelint-webpack-plugin/issues/102
- Remove chalk dep (not used anymore, stylelint already does the coloring)
- Add instances of Error to the compilation errors/warnings arrays
- Update tests
Closes https://github.com/JaKXz/stylelint-webpack-plugin/issues/102
=> fix: stylelint to webpack error output

package.json, test/.stylelintrc, yarn.lock
Employs the package upgrade from https://github.com/JaKXz/stylelint-webpack-plugin/pull/108, but also fixes the tests which were broken by the upgrade by removing dead rules from .stylelintrc
=> update stylelint and remove dead rules from tests

README.md
I searched a looong time for a bug related to this.
=> Add hint about 'option.files' needing to be relative

lib/lint-dirty-modules-plugin.js, package.json, yarn.lock
I run with `lintDirtyModulesOnly` option on Window, it doesn't work due to minimatch's problem on Window. After changing minimatch into micromatch it works fine in my case, and performance is a bit better.
=> Fix lintDirtyModulesOnly when matching path on Windows

README.md, lib/run-compilation.js, test/helpers/base-config.js, test/index.test.js, test/lib/lint-dirty-modules-plugin.test.js
Fixes #61.
nb: I could probably improve the commit message to better address the issue, but the main point is that this plugin should never call the `console.warn` function [which was the only way it would log before].
=> fix(console): console.warn should never be called

index.js, package.json
Fixes #153. Regression introduced in 0.10.4.
None. Restores peer version support for older webpack versions.
The next version of this module should be a major version, with a minimum webpack support of v4.6.0.
=> fix: fixes #153. webpack peerDep regression

src/index.js
Fix: #191
Currently, `options` variable is shallow copy. (`const { options } = this`)
When webpack has config multiple and `file` is relative, `.join(context, '/', file)` will be called multiple times.
So, `options.files` path is broken.
Nothing
=> fix: options variable in apply function

README.md, src/getOptions.js, src/options.json, test/formatter.test.js
The formatter option only accepted function, with this feature we can also set official formatters as string
```js
const StylelintPlugin = require('stylelint-webpack-plugin');
module.exports = {
// ...
plugins: [
new StylelintPlugin({
formatter: 'json' // See https://stylelint.io/user-guide/node-api#formatter
)
],
// ...
};
```
Resolve #201
=> feat: make possible to define official formatter as string

package-lock.json, src/utils.js
- [x ] **bugfix**
I often name my project folders using the pattern/scheme of `Client name (project name)` - first the name of the client and then in braces the name of his/her project.
However, as described in https://github.com/mrmlnc/fast-glob/issues/158 this raises a problem - even if I use `globbyOptions: {extension: false, extglob: false}` the problem persists. The solution is to properly escape all symbols inside the `context` which are treated specially by `Fast-Glob` - but leave them as is in the actual glob pattern(s) in `files`.
I am not sure whether my implementation is the optimal one but I am open to discussion.
This PR is not supposed to break anything - only to handle some edge cases.
I am using the plugin like this (inside `vue.config.js`)
```js …
```
=> Avoiding https://github.com/mrmlnc/fast-glob/issues/158

src/getOptions.js
It seems that the default value for the `files` option has an issue.
If the purpose of `**/*.s?(c|a)ss` is to match just `scss` or `sass` files so why we need `?` after `s`
I think the `**/*.(s(c|a)ss|css)` is better for supporting `css`, `scss` & `sass` files.
=> fix: use better micromatch extglobs

src/linter.js
Fix #214
I was doing a simple check, whether the file was in error or not.
Now I go through all the warnings and see if there are any error.
This fixes the issue with the options:
- [reportNeedlessDisables](https://stylelint.io/user-guide/usage/options/#reportneedlessdisables)
- [reportInvalidScopeDisables](https://stylelint.io/user-guide/usage/options/#reportinvalidscopedisables)
- [reportDescriptionlessDisables](https://stylelint.io/user-guide/usage/options/#reportdescriptionlessdisables)
This options above do not mark the file with error, but that launch warnings with error.
=> fix: display errors

README.md, package-lock.json, package.json
The `@types/stylelint` package is for Stylelint 13. Stylelint 14 includes type declarations already.
The issue with installing this dependency in a project that uses Stylelint 14+ is that it includes outdated "postcss" (v7) dependency that might cause issues in the host project.
For projects that are still using Stylelint 13 this could potentially be a breaking change (if the project interacts with stylelint related types directly). The fix would be to add `@types/stylelint` dependency manually in the project.
Even though this is potentially a breaking change, bumping to next major version is not really an option since it's already taken.
@ricardogobbosouza
=> fix: remove outdated stylelint types

src/StylelintError.js, src/linter.js
=> feat: add stylelint prefix to CLI output for better debugging

test/context.test.js, test/emit-error.test.js, test/emit-warning.test.js, test/empty.test.js, test/error.test.js, test/exclude.test.js, test/fail-on-config.test.js, test/fail-on-error.test.js, test/fail-on-warning.test.js, test/formatter.test.js, test/multiple-instances.test.js, test/ok.test.js, test/output-report.test.js, test/quiet.test.js, test/stylelint-ignore.test.js, test/stylelint-lint.test.js, test/stylelint-path.test.js, test/symbols.test.js, test/threads.test.js, test/utils/pack.js, test/warning.test.js
I'm working on #342 and when a test failed, it had to time out to display the error.
Using async/await makes it so that when a test fails, the error is printed immediately.
This reduces the feedback loop and makes it easier to make changes.
The downside is that it hides the webpack API behind an indirection layer.
I'll let you judge if this is something you want to have or not.
N/A
N/A
=> chore: improve unit tests feedback loop by making them asynchronous

.github/workflows/nodejs.yml, .gitignore, babel.config.js, lint-staged.config.js, package-lock.json, package.json, tsconfig.json
Minimum supported Node.js version is 18
Yes
No
=> build!: minimum supported Node.js version is 18

src/linter.js, test/output-report.test.js
The changes in https://github.com/webpack-contrib/stylelint-webpack-plugin/pull/300 broke the `outputReport` functionality, specifically:
```
-      const content = outputReport.formatter
-        ? loadFormatter(stylelint, outputReport.formatter)(results)
-        : formatter(results);
+      const content = outputReport.formatter;
+      loadFormatter(stylelint, outputReport.formatter)(results, returnValue);
+      formatter(results, returnValue);
```
means that the `content` that is written to the output file, is always just the `.toString()` of the `outputReport.formatter` itself.  For example:
```
outputReport: {
filePath: "stylelint-report.json"
formatter: "json",
}
> cat stylelint-report.json
json
```
I have not added additional tests for this change, as I am …
=> fix: output report generation

.husky/commit-msg, .husky/pre-commit, package-lock.json, package.json, types/getStylelint.d.ts, types/linter.d.ts
=> chore: update husky hooks
