webpack-contrib/stylelint-webpack-plugin

- package.json
resolve https://github.com/vieron/stylelint-webpack-plugin/issues/2
> npm: update libs

- package.json
inherited from sass-webpack-plugin
> npm: clean not used dependencies

- test/.badstylelintrc
- test/index.js
https://github.com/vieron/stylelint-webpack-plugin/issues/40
Created with the intent to highlight a problem with invalid JSON breaking/surfacing an unclear error
> implement unit test to highlight poor json config can break stylelint

- lib/run-compilation.js
- test/fixtures/test10/index.js
- test/fixtures/test10/test.scss
- test/index.js
Fix issue with logging error messages
> #50 No warning and error messages

- README.md
- index.js
> Remove configFile option in order to let cosmiconfig handle it.

- package.json
- yarn.lock
> chore(package): update mocha to version 4.0.1

- README.md
- lib/run-compilation.js
- package.json
- test/index.test.js
- yarn.lock
see [#103](https://github.com/JaKXz/stylelint-webpack-plugin/issues/103)
> changes to support webpack/webpack-dev-server from hard-failing on error messages

- package.json
> fix(package): update micromatch to version 3.1.8

- src/LintDirtyModulesPlugin.js
- test/lint-dirty-modules-only.test.js
> fix: convert back-slashes

- src/index.js
- src/linter.js
- test/LintDirtyModulesPlugin.test.js
- test/lint-dirty-modules-only.test.js
> fix: hooks

- package-lock.json
- package.json
> feat: support stylelint v12

- package.json
- src/LintDirtyModulesPlugin.js
- test/LintDirtyModulesPlugin.test.js
Resolve #187 
Resolve #190 
no
Thanks @vankop for starting PR #190
> fix: support webpack 5

- src/index.js
https://github.com/nuxt-community/stylelint-module/issues/33
No
No
> fix: compatibility stylelint v13

- src/LintDirtyModulesPlugin.js
> fix: replace back slashes on changed files

- src/LintDirtyModulesPlugin.js
- src/index.js
- src/linter.js
- src/utils.js
- test/LintDirtyModulesPlugin.test.js
- Require lint of stylelint only one time
- Create utils with helper functions
No
No
> refactor: require lint of stylelint only one time and create utils with helper functions

- CHANGELOG.md
- declarations/LintDirtyModulesPlugin.d.ts
- declarations/StylelintError.d.ts
- declarations/cjs.d.ts
- declarations/getOptions.d.ts
- declarations/index.d.ts
- declarations/linter.d.ts
- declarations/utils.d.ts
- lint-staged.config.js
- package-lock.json
- package.json
- src/LintDirtyModulesPlugin.js
- src/StylelintError.js
- src/getOptions.js
- src/index.js
- src/linter.js
- src/utils.js
- tsconfig.json
> feat: support typescript

- package-lock.json
- package.json
- src/getOptions.js
Updated `schema-utils`
Updated dependencies
No
No
> chore: updated schema-utils

- README.md
#216 introduced a new default value for files option. This commit
reflects the change
Readme contains an outdated value
None
> docs: fix files option's default value

- .github/workflows/nodejs.yml
- README.md
- declarations/index.d.ts
- declarations/utils.d.ts
- package-lock.json
- package.json
- src/index.js
- src/utils.js
> fix: performance

- .github/workflows/nodejs.yml
- README.md
- babel.config.js
- declarations/index.d.ts
- declarations/utils.d.ts
- jest.config.js
- package-lock.json
- package.json
- src/index.js
- src/utils.js
- test/empty.test.js
- test/watch.test.js
Resolve #231 
- Webpack v4 dropped
- Node.js v10 dropped
- Webpack v4 dropped
- Node.js v10 dropped
No
> refactor!: webpack v4 and nodejs v10 dropped

- declarations/utils.d.ts
- package-lock.json
- package.json
- src/index.js
- src/linter.js
- src/utils.js
fixes #239
No
Same notes for jsdoc as in `eslint-webpack-plugin`
> fix: crash with `ERR_REQUIRE_ESM` error

- .github/workflows/nodejs.yml
> chore: use npm cache in ci

- README.md
https://github.com/webpack-contrib/stylelint-webpack-plugin/blob/5858406c49381c4643260d8badbfac2b28009c74/src/options.js#L43-L45
Documented defaults are incorrect
> docs: fix incorrect defaults

- .github/ISSUE_TEMPLATE/BUG.md
- .github/ISSUE_TEMPLATE/DOCS.md
- .github/ISSUE_TEMPLATE/FEATURE.md
- .github/ISSUE_TEMPLATE/MODIFICATION.md
- .github/ISSUE_TEMPLATE/SUPPORT.md
Update issue templates to match with other webpack-contrib repositories.
None
No
> docs: update issue templates

- README.md
- package-lock.json
- package.json
> fix: remove outdated stylelint types

- jest.config.js
- src/getStylelint.js
- src/index.js
- src/linter.js
- test/fixtures/stylelintignore/.stylelintignore
- test/fixtures/stylelintignore/ignore.scss
- test/fixtures/stylelintignore/index.js
- test/fixtures/stylelintignore/test.scss
- test/mock/stylelint/index.js
- test/stylelint-ignore.test.js
- test/stylelint-lint.test.js
Files ignored in `.stylelintignore` when changed were going through lint
Resolve #257 
No
Stylelint has an api to check if the file is ignored [`isPathIgnored`](https://github.com/stylelint/stylelint/blob/main/lib/createStylelint.js#L43)
> fix: ignored file

- README.md
- package-lock.json
You don't need to “install” when using yarn add
> docs(readme): remove install when using yarn add

- .github/workflows/nodejs.yml
> ci: update

- src/getStylelint.js
- types/getStylelint.d.ts
> fix: types

- src/StylelintError.js
- src/linter.js
CLI output (especially errors) of stylelint-webpack-plugin are easily identifiable as coming from this plugin.
No
No
> [2.x] feat: add stylelint prefix to CLI output for better debugging

- src/index.js
- types/index.d.ts
Parse options only one time
No
No
> perf: parse options only one time

- .github/workflows/nodejs.yml
- README.md
- babel.config.js
- package-lock.json
- package.json
Resolve #283 
Drop node v12
Yes
No
> build!: drop node v12

- README.md
Update note in readme.md file
No
> chore: enhance readme.md

- src/index.js
- src/linter.js
> chore: increase coverage

- README.md
Updated Webpack compatibility note so that it doesn't point that this is stylelint-webpack-plugin version 3.0 anymore. In fact, it does not mention any version right now to avoid such discrepancies in the future.
No
No
> docs(readme): update webpack compatibility note

- .github/workflows/nodejs.yml
- package-lock.json
> ci: add node 24
